# See: https://docs.readthedocs.io/en/latest/yaml-config.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - echo "Creating environment"
    post_build:
      - echo "Build finished successfully"
      - echo `date`

python:
  install:
    - requirements: docs/requirements.txt

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false
