services:
    ebel:
        build: .
        restart: always
        container_name: ebel_ebel
        ports: 
            - 5000:5000
        depends_on:
            - mysql
            - orientdb
        volumes:
            - ebel_data:/root/.ebel/
    mysql:
        image: mysql:8.0.24
        restart: always
        container_name: ebel_mysql
        ports:
            - 3606:3606
        environment: 
            MYSQL_ROOT_PASSWORD: ebel
            MYSQL_USER: ebel
            MYSQL_PASSWORD: ebel
            MYSQL_DATABASE: ebel
        volumes:
            - ebel_mysql:/var/lib/mysql
    orientdb:
        image: orientdb:3.2.0
        restart: always
        container_name: ebel_orientdb
        environment:
            - ORIENTDB_ROOT_PASSWORD=ebel
        ports:           
            - 2424:2424
            - 2480:2480
        volumes: 
            - ebel_orientdb_db:/orientdb/databases
            - ebel_orientdb_backup:/orientdb/backup
            - ebel_orientdb_config:/orientdb/config
    phpmyadmin:
        image: phpmyadmin:5.1.0
        restart: always
        container_name: ebel_phpmyadmin
        ports:
            - 8089:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql

volumes:
    ebel_orientdb_db:
    ebel_orientdb_backup:
    ebel_mysql:
    ebel_orientdb_config:
    ebel_data: